# Generated by Django 3.0.8 on 2020-08-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20200818_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked',
            field=models.ManyToManyField(related_name='liked_posts', to='network.Post'),
        ),
    ]
